-- Migration 001 — initial schema snapshot.
--
-- Captures the full schema as of the migration framework's introduction.
-- All statements are individually idempotent (CREATE IF NOT EXISTS,
-- ALTER ADD COLUMN IF NOT EXISTS, DO $$ guarded blocks) so applying
-- this file to an EXISTING dev DB that grew out of the older
-- init_db-direct pattern is a no-op — it just records the migration
-- as applied so subsequent migrations sequence correctly.
--
-- DO NOT edit this file after release. New schema changes get their
-- own numbered migration files (002_..., 003_..., etc.) appended.

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS archives (
    id TEXT PRIMARY KEY,
    url TEXT NOT NULL,
    url_hash TEXT NOT NULL,
    title TEXT,
    text_content TEXT,
    search_vector tsvector GENERATED ALWAYS AS (
        setweight(to_tsvector('english', coalesce(title, '')), 'A') ||
        setweight(to_tsvector('english', coalesce(text_content, '')), 'B') ||
        setweight(to_tsvector('english', coalesce(url, '')), 'C')
    ) STORED,
    status TEXT NOT NULL DEFAULT 'pending',
    tier TEXT NOT NULL DEFAULT 'chromium',
    source TEXT NOT NULL DEFAULT 'direct',
    error_message TEXT,
    artifact_dir TEXT,
    content_hash TEXT,
    screenshot_hash TEXT,
    revisit_of TEXT REFERENCES archives(id),
    snapshot_size BIGINT,
    warc_size BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    completed_at TIMESTAMPTZ,
    metadata JSONB,
    removed_at TIMESTAMPTZ,
    removed_reason TEXT,
    submitter_ip_hash TEXT
);

-- Add columns to existing databases (idempotent)
ALTER TABLE archives ADD COLUMN IF NOT EXISTS removed_at TIMESTAMPTZ;
ALTER TABLE archives ADD COLUMN IF NOT EXISTS removed_reason TEXT;
ALTER TABLE archives ADD COLUMN IF NOT EXISTS submitter_ip_hash TEXT;
-- Drop old raw-IP columns if upgrading from an earlier version (privacy fix)
ALTER TABLE archives DROP COLUMN IF EXISTS submitter_ip;
ALTER TABLE archives DROP COLUMN IF EXISTS submitter_ip_hashed;

CREATE INDEX IF NOT EXISTS idx_archives_url_hash ON archives(url_hash);
CREATE INDEX IF NOT EXISTS idx_archives_status ON archives(status);
CREATE INDEX IF NOT EXISTS idx_archives_created_at ON archives(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_archives_content_hash ON archives(content_hash);
CREATE INDEX IF NOT EXISTS idx_archives_removed_at ON archives(removed_at);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_indexes WHERE indexname = 'idx_archives_search'
    ) THEN
        CREATE INDEX idx_archives_search ON archives USING GIN(search_vector);
    END IF;
END$$;

CREATE TABLE IF NOT EXISTS jobs (
    id TEXT PRIMARY KEY,
    archive_id TEXT NOT NULL REFERENCES archives(id) ON DELETE CASCADE,
    status TEXT NOT NULL DEFAULT 'queued',
    tier TEXT NOT NULL DEFAULT 'chromium',
    priority INTEGER NOT NULL DEFAULT 0,
    attempts INTEGER NOT NULL DEFAULT 0,
    max_attempts INTEGER NOT NULL DEFAULT 3,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    started_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    error_message TEXT,
    locked_by TEXT,
    locked_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_jobs_archive_id ON jobs(archive_id);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_indexes WHERE indexname = 'idx_jobs_claimable'
    ) THEN
        CREATE INDEX idx_jobs_claimable ON jobs(priority DESC, created_at)
            WHERE status = 'queued';
    END IF;
END$$;

CREATE TABLE IF NOT EXISTS audit_log (
    id TEXT PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    action TEXT NOT NULL,
    archive_id TEXT REFERENCES archives(id) ON DELETE SET NULL,
    admin_user TEXT,
    ip_address_hash TEXT,
    details JSONB
);
-- Rename on upgrade if coming from earlier schema (idempotent)
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.columns
               WHERE table_name='audit_log' AND column_name='ip_address')
       AND NOT EXISTS (SELECT 1 FROM information_schema.columns
                       WHERE table_name='audit_log' AND column_name='ip_address_hash') THEN
        ALTER TABLE audit_log RENAME COLUMN ip_address TO ip_address_hash;
    END IF;
END$$;

CREATE INDEX IF NOT EXISTS idx_audit_log_created_at ON audit_log(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_audit_log_archive_id ON audit_log(archive_id);

CREATE TABLE IF NOT EXISTS reports (
    id TEXT PRIMARY KEY,
    archive_id TEXT NOT NULL REFERENCES archives(id) ON DELETE CASCADE,
    reason TEXT NOT NULL,
    details TEXT,
    reporter_email TEXT,
    reporter_ip_hash TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    status TEXT NOT NULL DEFAULT 'pending',
    resolved_at TIMESTAMPTZ,
    resolved_by TEXT,
    resolution_notes TEXT
);
-- Rename on upgrade (idempotent)
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.columns
               WHERE table_name='reports' AND column_name='reporter_ip')
       AND NOT EXISTS (SELECT 1 FROM information_schema.columns
                       WHERE table_name='reports' AND column_name='reporter_ip_hash') THEN
        ALTER TABLE reports RENAME COLUMN reporter_ip TO reporter_ip_hash;
    END IF;
END$$;

CREATE INDEX IF NOT EXISTS idx_reports_status ON reports(status);
CREATE INDEX IF NOT EXISTS idx_reports_archive_id ON reports(archive_id);
CREATE INDEX IF NOT EXISTS idx_reports_created_at ON reports(created_at DESC);

-- Per-proxy gate-pass status. Separate from the live ProxyRotator's
-- in-memory failure set so we can prefer known-good exits across
-- worker restarts.
CREATE TABLE IF NOT EXISTS proxy_status (
    proxy_server TEXT PRIMARY KEY,
    last_checked_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    gate_passing BOOLEAN NOT NULL DEFAULT false,
    asn_org TEXT,
    country_code TEXT,
    consecutive_failures INTEGER NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_proxy_status_passing
    ON proxy_status(last_checked_at DESC) WHERE gate_passing = true;

-- Per-instance privacy-frontend content-verification state.
-- Populated by the worker's _frontend_probe_loop — only instances
-- where a canonical test URL renders with the expected marker are
-- marked passing. Reads at capture time filter on
-- (target_apex, content_verified) to skip dead / gated frontends.
--
-- Composite PK (frontend_base, target_apex): a single instance can
-- front multiple apexes (xcancel.com serves both twitter.com and
-- x.com). Each (instance, apex) tuple is probed and recorded
-- independently — even though the probe outcome is usually the same,
-- we shouldn't conflate them at the DB level.
CREATE TABLE IF NOT EXISTS frontend_status (
    frontend_base TEXT NOT NULL,
    target_apex TEXT NOT NULL,
    content_verified BOOLEAN NOT NULL DEFAULT false,
    last_checked_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    consecutive_failures INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY (frontend_base, target_apex)
);
-- Migrate dev DBs that picked up the original frontend_base-only PK.
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.table_constraints
        WHERE table_name = 'frontend_status'
          AND constraint_type = 'PRIMARY KEY'
          AND constraint_name = 'frontend_status_pkey'
    ) AND NOT EXISTS (
        SELECT 1 FROM information_schema.key_column_usage
        WHERE table_name = 'frontend_status'
          AND constraint_name = 'frontend_status_pkey'
          AND column_name = 'target_apex'
    ) THEN
        ALTER TABLE frontend_status DROP CONSTRAINT frontend_status_pkey;
        ALTER TABLE frontend_status
            ADD PRIMARY KEY (frontend_base, target_apex);
    END IF;
END$$;
CREATE INDEX IF NOT EXISTS idx_frontend_status_verified
    ON frontend_status(target_apex, last_checked_at DESC)
    WHERE content_verified = true;

-- Per-apex tier-outcome counters. Populated on every capture completion
-- (win or loss) so future routing decisions can be empirical rather than
-- relying on stated policy (robots.txt) or static priors. Keys on the
-- hostname-minus-www routing key from url.apex_of(), not a true PSL apex.
CREATE TABLE IF NOT EXISTS domain_observations (
    apex TEXT PRIMARY KEY,
    first_seen_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_seen_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    tier_wins JSONB NOT NULL DEFAULT '{}'::jsonb,
    tier_losses JSONB NOT NULL DEFAULT '{}'::jsonb,
    last_winning_tier TEXT
);
CREATE INDEX IF NOT EXISTS idx_domain_observations_last_seen
    ON domain_observations(last_seen_at DESC);

-- Persistent cookie cache keyed by (domain, proxy). Empty proxy_server
-- means direct connection. Stores solved cf_clearance so the next
-- capture through the same (domain, proxy) skips the challenge.
CREATE TABLE IF NOT EXISTS cf_clearance_cache (
    domain TEXT NOT NULL,
    proxy_server TEXT NOT NULL DEFAULT '',
    cookie_name TEXT NOT NULL,
    cookie_value TEXT NOT NULL,
    cookie_path TEXT NOT NULL DEFAULT '/',
    expires_at TIMESTAMPTZ NOT NULL,
    set_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (domain, proxy_server, cookie_name)
);
CREATE INDEX IF NOT EXISTS idx_cf_clearance_expires
    ON cf_clearance_cache(expires_at);
