#!/usr/bin/env bash
# ABOUTME: Interactive setup for public deployment — generates .env with secrets
set -euo pipefail

cd "$(dirname "$0")/.."

if [[ -f .env ]]; then
    read -rp ".env already exists. Overwrite? [y/N] " yn
    [[ "$yn" =~ ^[Yy]$ ]] || { echo "aborted"; exit 1; }
fi

echo "=== Unstoppable Archive — public deployment setup ==="
echo

# Admin password
read -rsp "Admin password (min 8 chars): " ADMIN_PW
echo
if [[ ${#ADMIN_PW} -lt 8 ]]; then
    echo "error: password too short" >&2
    exit 1
fi
read -rsp "Confirm: " ADMIN_PW_CONFIRM
echo
[[ "$ADMIN_PW" == "$ADMIN_PW_CONFIRM" ]] || { echo "error: passwords do not match" >&2; exit 1; }

echo "Generating bcrypt hash..."
ADMIN_HASH=$(echo -n "$ADMIN_PW" | docker compose run --rm -T app uv run python scripts/hash_password.py | tail -1)

# Secrets
echo "Generating session secret..."
SESSION_SECRET=$(openssl rand -hex 32)

echo "Generating DB password..."
DB_PASSWORD=$(openssl rand -hex 24)

# Optional blocklist
echo
read -rp "Enable StevenBlack porn blocklist? [Y/n] " bl
if [[ ! "$bl" =~ ^[Nn]$ ]]; then
    BLOCKLIST_URL="https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/porn/hosts"
else
    BLOCKLIST_URL=""
fi

# Write .env
cat > .env <<EOF
# Generated by scripts/setup-public.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
ARCHIVER_DB_PASSWORD=$DB_PASSWORD
ARCHIVER_ADMIN_PASSWORD_HASH=$ADMIN_HASH
ARCHIVER_SESSION_SECRET=$SESSION_SECRET
ARCHIVER_BLOCKLIST_URLS=$BLOCKLIST_URL
ARCHIVER_BLOCKLIST_DOMAINS=
ARCHIVER_ALLOWLIST_DOMAINS=
ARCHIVER_CAPTCHA_PROVIDER=none
EOF

chmod 600 .env

echo
echo "=== Setup complete ==="
echo "Wrote .env (mode 600)"
echo
echo "Next steps:"
echo "  1. Review .env — add any additional blocklist URLs or allowlist overrides"
echo "  2. Set up HTTPS reverse proxy (see deploy/Caddyfile.example)"
echo "  3. Start the stack:"
echo "       make run-public"
echo "  4. Visit https://your-domain/admin/ and log in"
echo "  5. Check /admin/ dashboard to confirm blocklist loaded"
