#!/usr/bin/env bash
# ABOUTME: Interactive setup for public deployment — generates .env with secrets
set -euo pipefail

cd "$(dirname "$0")/.."

if [[ -f .env ]]; then
    read -rp ".env already exists. Overwrite? [y/N] " yn
    [[ "$yn" =~ ^[Yy]$ ]] || { echo "aborted"; exit 1; }
fi

echo "=== Unstoppable Archive — public deployment setup ==="
echo

# Admin password
read -rsp "Admin password (min 8 chars): " ADMIN_PW
echo
if [[ ${#ADMIN_PW} -lt 8 ]]; then
    echo "error: password too short" >&2
    exit 1
fi
read -rsp "Confirm: " ADMIN_PW_CONFIRM
echo
[[ "$ADMIN_PW" == "$ADMIN_PW_CONFIRM" ]] || { echo "error: passwords do not match" >&2; exit 1; }

echo "Generating bcrypt hash..."
# --no-deps: hash_password.py needs no database, and letting compose
# start postgres here would initialize the pgdata volume with the dev
# password from the base file — .env with the real password doesn't
# exist yet, and postgres only applies POSTGRES_PASSWORD on first init.
# printf over echo -n: echo mangles passwords containing backslashes.
ADMIN_HASH=$(printf '%s' "$ADMIN_PW" | docker compose run --rm -T --no-deps app uv run python scripts/hash_password.py | tail -1)

# Secrets
echo "Generating session secret..."
SESSION_SECRET=$(openssl rand -hex 32)

echo "Generating DB password..."
DB_PASSWORD=$(openssl rand -hex 24)

echo "Generating API key (destructive operations, e.g. archive deletion)..."
API_KEY=$(openssl rand -hex 32)

# Public domain + ACME contact email — required for the bundled Caddy
# service to provision Let's Encrypt TLS. DNS for $PUBLIC_DOMAIN must
# resolve to this host before starting the stack or the ACME HTTP-01
# challenge fails and Caddy retries with backoff.
echo
read -rp "Public domain (e.g. archive.example.com): " PUBLIC_DOMAIN
[[ -n "$PUBLIC_DOMAIN" ]] || { echo "error: domain required" >&2; exit 1; }
read -rp "ACME contact email (for cert expiry alerts): " ACME_EMAIL
[[ "$ACME_EMAIL" =~ @ ]] || { echo "error: invalid email" >&2; exit 1; }

# Optional blocklist
echo
read -rp "Enable StevenBlack porn blocklist? [Y/n] " bl
if [[ ! "$bl" =~ ^[Nn]$ ]]; then
    BLOCKLIST_URL="https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/porn/hosts"
else
    BLOCKLIST_URL=""
fi

# Write .env
cat > .env <<EOF
# Generated by scripts/setup-public.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
ARCHIVER_DB_PASSWORD=$DB_PASSWORD
ARCHIVER_ADMIN_PASSWORD_HASH=$ADMIN_HASH
ARCHIVER_SESSION_SECRET=$SESSION_SECRET
ARCHIVER_API_KEY=$API_KEY
ARCHIVER_PUBLIC_DOMAIN=$PUBLIC_DOMAIN
ARCHIVER_ACME_EMAIL=$ACME_EMAIL
ARCHIVER_BLOCKLIST_URLS=$BLOCKLIST_URL
ARCHIVER_BLOCKLIST_DOMAINS=
ARCHIVER_ALLOWLIST_DOMAINS=
ARCHIVER_CAPTCHA_PROVIDER=none
EOF

chmod 600 .env

echo
echo "=== Setup complete ==="
echo "Wrote .env (mode 600)"

# Postgres applies POSTGRES_PASSWORD only when it initializes a fresh
# volume. If the stack ever ran with the dev defaults, the existing
# volume keeps the old password and app/worker will fail to auth.
if docker volume inspect archiver_pgdata >/dev/null 2>&1; then
    echo
    echo "WARNING: existing database volume 'archiver_pgdata' found."
    echo "If this stack previously ran with dev credentials, the new DB"
    echo "password will NOT apply. To start fresh (DELETES archived data):"
    echo "    docker compose down && docker volume rm archiver_pgdata"
fi
echo
echo "Next steps:"
echo "  1. Point DNS A/AAAA for $PUBLIC_DOMAIN at this host"
echo "  2. Make sure ports 80/443 are reachable (firewall, NAT, etc.)"
echo "  3. Start the stack:"
echo "       make run-public"
echo "  4. Caddy will request a Let's Encrypt cert on first request"
echo "     (watch logs:  docker compose logs caddy -f)"
echo "  5. Visit https://$PUBLIC_DOMAIN/admin/ and log in"
